config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => 'public#home'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'public/about'
  get 'public/team'
  get 'public/listing'
  get 'public/listing_detail'
  get 'public/gallery'
  get 'public/cart'

  # resource :cart, only: [:show]
  resources :order_items, only: [:create, :destroy]

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :products do
    member do
      get :delete, :toggle_visible
    end
  end
  
  resources :listings do
    member do
      get :delete, :toggle_visible
    end
  end

  resources :teams do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
	acts_as_list :scope => :product
	belongs_to :product
	has_many :order_items

	scope :visible, lambda { where(:visible => true) }
	scope :invisible, lambda { where(:visible => false) }
	scope :sorted, lambda { order("name ASC") }
	scope :newest_first, lambda { order("created_at DESC") }

  	validates :name, :presence => true,
					 :length => { :maximum => 255 },
					 :uniqueness => {:case_sensitive => false, :scope => :product_id}
	validates_presence_of :short_desc
	validates_presence_of :long_desc

	validates :orig_price, :presence => true,
						   :numericality => true
		 
	validates :curr_price, :numericality => true

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_product
  before_action :set_listing_count, :only => [:new, :create, :edit, :update]

  def index
    @listings = @product.listings.sorted
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new(:product_id => @product.id)
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.product = @product 
    @listing.image_loc = File.join("listings", @listing.name.downcase.gsub!(/\s+/, '') + ".jpg")
    if @listing.save
      flash[:notice] = "Listing created successfully."
      redirect_to(listings_path(:product_id => @product.id))
    else
      render "new.js.erb"
    end 
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(listing_params)
      flash[:notice] = "Listing '#{@listing.name}' updated successfully."
      redirect_to(listings_path(:product_id => @product.id))
    else
      render "edit.js.erb"
    end
  end

  def toggle_visible
    @listing = Listing.find(params[:id])
    @listing.toggle(:visible)
    @listing.save
    flash[:notice] = "Listing visibility toggled successfully."
    respond_to do |format|
        format.js
    end
  end

  def delete
    @listing = Listing.find(params[:id])
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:notice] = "Listing '#{@listing.name}' destroyed successfully."
    redirect_to(listings_path(:product_id => @product.id))   
  end

private

  def listing_params
    params.require(:listing).permit(:product_id, :name, 
              :short_desc, :long_desc, :visible, :orig_price, :curr_price, :image_loc, :position)
  end

  def find_product
    @product = Product.find(params[:product_id])
  end

  def set_listing_count
    @listing_count = @product.listings.count
    if params[:action] == 'new' || params[:action] == 'create'
      @listing_count += 1
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 class="text-danger">Delete Listing</h3>
    </div>
    <div class="modal-body">
      <ul class="errors"></ul>
      Are you sure you wish to delete <b><%= @listing.name %></b>?
    </div>
    <div class="modal-footer">
      <%= link_to "Yes, Delete This Listing", listing_path(@listing,:product_id => @product.id), method: :delete, remote: true, class: "btn btn-danger" %>
      <%= link_to "No, Please Don't", "#", class: "btn btn-success", data: { dismiss: "modal" } %>
    </div>
  </div>
</div>

app/views/listings/_edit.html.erb
<div class="container">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			  	<h3 class="text-success"><%= "#{@listing.name}" %></h3>
			</div>
			<%= form_for(@listing, 
				:url => listing_path(@listing, :product_id => @product.id), 
				remote: true, 
				html: { style: "display:inline;" }) do |f| %>
				<%= error_messages_for(f.object) %>
				<%= render(:partial => 'form', :locals => {:f => f}) %> 
			<% end %>
		</div>
	</div>
</div>

app/views/listings/_form.html.erb
<div class="modal-body">
    <ul class="errors"></ul>
    <div class="row">
        <div class="col-sm-6" style="padding-bottom: 10px;">
            <%= f.text_field(:name, class: 'text-cp form-control', placeholder: 'Listing Name') %>
        </div>
        <div class="col-sm-3" style="padding-bottom: 10px;">
            <%= f.select(:position, 1..@listing_count, {class: 'form-control'}) %> (position)
        </div>
        <div class="col-sm-3 text-danger" style="padding-bottom: 10px;">
            <%= f.select(:visible, [ ["Visible", true], ["Invisible", false]], {}, {class: 'form-control'}) %>
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.text_field(:short_desc, class: 'form-control', placeholder: 'Enter Brief Description') %>
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.text_area(:long_desc, class: 'form-control', rows:'6',  placeholder: 'Describe in details...') %>
        </div>
        <div class="col-sm-6 text-center text-danger" style="padding-bottom: 10px;">
            <div class="input-group">
                <span class="input-group-addon">Original Price (INR)</span>
                <%= f.number_field(:orig_price, class: 'form-control') %> 
            </div>
        </div>
        <div class="col-sm-6 text-center text-danger" style="padding-bottom: 10px;">
            <div class="input-group">
                <span class="input-group-addon">Current Price (INR)</span>
                <%= f.number_field(:curr_price, class: 'form-control') %>
            </div> 
        </div>
        <% if !@listing.new_record? %>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.text_field(:image_loc, class: 'form-control', placeholder: 'Image location') %>
        </div>
        <% end %>
    </div>
</div>
<div class="modal-footer">
    <%= link_to "Close", "#", class: "btn btn-secondary", data: {dismiss: "modal"} %>
    <%= f.submit "Submit" ,class: "btn btn-primary" %>
</div>

app/views/listings/_index.html.erb
<% @listings.each do |listing| %>
<tr>
    <td><%= listing.position %></td>
     <td>
      <%= listing.name %>
      <% if listing.visible %>
          <%= link_to(toggle_visible_listing_path(listing,:product_id => @product.id), 
              :remote => true) do %>
              <i class="fa fa-eye fa-fw" aria-hidden="true"></i>
          <% end %>  
      <% else %>
          <%= link_to(toggle_visible_listing_path(listing,:product_id => @product.id), 
              :remote => true) do %>
              <i class="fa fa-eye-slash fa-fw" aria-hidden="true"></i>
          <% end %>   
      <% end %> 
      <% if check_image(listing.image_loc) %>
           <i class="fa fa-camera fa-fw" aria-hidden="true"></i>
      <% end %>
    </td>  
    <td>
      <%= number_to_currency(listing.orig_price, 
        :unit => "INR", :format => "%u %n") %>      
    </td>
    <td>
      <%= number_to_currency(listing.curr_price, 
        :unit => "INR", :format => "%u %n") %>    
    </td>
    <td>
      <%= link_to(listing_path(listing,:product_id => @product.id), 
          :remote => true, 
          :class => "btn btn-info btn-circle") do %>
          <i class="fa fa-flag fa-fw" aria-hidden="true"></i> 
      <% end %>  
      <%= link_to(edit_listing_path(listing, :product_id => @product.id), 
          :remote => true, 
          :class => "btn btn-success btn-circle") do %>
          <i class="fa fa-edit fa-fw" aria-hidden="true"></i> 
      <% end %>  
      <%= link_to(delete_listing_path(listing,:product_id => @product.id), 
          :remote => true, 
          :class => "btn btn-danger btn-circle") do %>
          <i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> 
      <% end %>       
    </td>
</tr>
<% end %>

app/views/listings/_new.html.erb
<div class="container">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 class="text-warning">Add Listing</h3>
			</div>
			<%= form_for(@listing, 
				:url => listings_path(@listing, :product_id => @product.id), 
				remote: true, 
				html: { style: "display:inline;" }) do |f| %>
				<%= error_messages_for(f.object) %>
				<%= render(:partial => 'form', :locals => {:f => f}) %> 
			<% end %>
		</div>
	</div>
</div>

app/views/listings/_save.js.erb
$("ul.errors").html("")
<% if @listing.errors.any? %>
  <% @listing.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".listing-index").html("<%= j (render 'index') %>")
  $("#listing-modal").modal("hide")
<% end %>

app/views/listings/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 class="text-info"><%= @listing.name %> 
        <%= images(@listing.image_loc, {class: "img-responsive", size: "200x200"}, "listing") %></h3>   
    </div>
    <div class="modal-body">
      <strong>Image Location: </strong> <small><%= @listing.image_loc %></small>
      <h4>Description Header:</h4>
      <p class="text-muted"><%= @listing.short_desc %></p>
      <h4>Description Body:</h4>
      <p class="text-muted"><%= @listing.long_desc %></p>
      <h4>Original Price:</h4>
      <p class="text-danger"><%= number_to_currency(@listing.orig_price, 
          :unit => "INR", :format => "%u %n") %></p>
      <h4>Current Price:</h4>
      <p class="text-danger"><%= number_to_currency(@listing.curr_price, 
          :unit => "INR", :format => "%u %n") %></p>
      <p>
    </div>
    <div class="modal-footer">
      <%= link_to "Close", "#", class: "btn btn-secondary", data: {dismiss: "modal"} %>
    </div>
  </div>
</div>

app/views/listings/delete.js.erb
$("#listing-modal").html("<%= j (render 'delete') %>")
$("#listing-modal").modal("show")

app/views/listings/edit.js.erb
$("#listing-modal").html("<%= j (render 'edit') %>")
$("#listing-modal").modal("show")

app/views/listings/index.html.erb
<% @page_title = "All Listings" %>

<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header text-danger">
      <i class="fa fa-th-list"></i> 
      Listings for 
        <u><%= @product.name %></u>
      <span class="badge"><%= @listings.count %></span>
    </h3>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-laptop"></i><%= link_to "Dashboard", admin_path %>
      </li>
      <li>
        <i class="fa-th-list"></i><%= link_to "Categories", products_path %>
      </li>
      <li><i class="fa fa-th-list"></i>Listings</li>                
    </ol>
  </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
              <p>
              <%= link_to(new_listing_path(:product_id => @product.id),
                  remote: true,
                  class: "btn btn-success btn-sm") do %>
                  <span class="btn-label">
                    <i class="fa fa-plus"></i> 
                  </span> Listing
              <% end %>
              </p>
            </header>
            
            <table class="table table-striped table-advance table-hover" id="dataTables-listing">
             <thead>
                <tr>
                  <th>#</th>
                  <th>Listing</th>
                  <th>Original Price</th>
                  <th>Current Price</th>
                  <th><i class="fa fa-wrench"></i> Action</th>
                </tr>                           
             </thead>
            <tbody class="listing-index">
              <%= render "index" %>
            </tbody>
          </table>
        </section>
    </div>
</div>
<div id="listing-modal" class="modal fade"></div>

app/views/listings/new.js.erb
$("#listing-modal").html("<%= j (render 'new') %>")
$("#listing-modal").modal("show")

app/views/listings/show.js.erb
$("#listing-modal").html("<%= j (render 'show') %>")
$("#listing-modal").modal("show")

app/views/listings/toggle_visible.js.erb
location.reload();

app/views/listings/update.js.erb
<%= render "save" %>