config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => 'public#home'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'public/about'
  get 'public/team'
  get 'public/listing'
  get 'public/listing_detail'
  get 'public/gallery'
  get 'public/cart'

  # resource :cart, only: [:show]
  resources :order_items, only: [:create, :destroy]

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :products do
    member do
      get :delete, :toggle_visible
    end
  end
  
  resources :listings do
    member do
      get :delete, :toggle_visible
    end
  end

  resources :teams do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin/_footer.html.erb
<div class="text-right">
	<div class="credits">
		<a href="#">&copy; Sutirtha Chakraborty. All rights reserved.</a>
	</div>
</div>

app/views/layouts/admin/_header.html.erb
<header class="header dark-bg">
    <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="fa fa-bars"></i></div>
    </div>

    <!--logo start-->
    <%= link_to(admin_path, class: "logo" ) do %>
        Site <span class="lite">Administration</span>
    <% end %>
    <!--logo end-->

    <div class="nav search-row" id="top_menu">
        <!--  search form start -->
        <ul class="nav top-menu">                    
            <li>
                <form class="navbar-form">
                    <input class="form-control" placeholder="Search" type="text" disabled>
                </form>
            </li>                    
        </ul>
        <!--  search form end -->                
    </div>

    <div class="top-nav notification-row">                
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu  hidden-xs">
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="username"><%= session[:username].upcase_first %></span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <div class="log-arrow-up"></div>
                    <li class="eborder-top">
                        <%= link_to access_logout_path do %>
                            <i class="fa fa-sign-out fa-fw"></i> Logout
                        <% end %>
                    </li>
                </ul>
            </li>
            <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
    </div>
</header>      

app/views/layouts/admin/_sidebar.html.erb
<aside>
  <div id="sidebar" class="nav-collapse ">
      <!-- sidebar menu start-->
      <ul class="sidebar-menu">                
          <li class="">
            <%= link_to admin_path do %>
              <i class="fa fa-laptop"></i>
              <span>Dashboard</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to admin_users_path do %>
              <i class="fa fa-user"></i>
              <span>Admin</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to teams_path do %>
              <i class="fa fa-group"></i>
              <span>Team</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to products_path do %>
              <i class="fa fa-th-list"></i>
              <span>Categories</span>
            <% end %> 
          </li>
          <li class="">
            <%= link_to access_logout_path do %>
              <i class="fa fa-sign"></i>
              <span>Logout</span>
            <% end %>  
          </li>
      </ul>
      <!-- sidebar menu end-->
  </div>
</aside>