config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => 'public#home'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'public/about'
  get 'public/team'
  get 'public/listing'
  get 'public/listing_detail'
  get 'public/gallery'
  get 'public/cart'

  # resource :cart, only: [:show]
  resources :order_items, only: [:create, :destroy]

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :products do
    member do
      get :delete, :toggle_visible
    end
  end
  
  resources :listings do
    member do
      get :delete, :toggle_visible
    end
  end

  resources :teams do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/app/_cart_text.html.erb
<%= link_to(public_cart_path) do %>
	<i class="fa fa-shopping-cart"></i> 
	<%= "(" + current_order.order_items.size.to_s + ")" %>
<% end %>

app/views/layouts/app/_footer.html.erb
<footer>
	<div class="copyright" id="footer">
	  <div class="container">
	    <div class="col-md-6">
	        <p>All contents &copy; 2017 <a href="http://astro.com">Astro.com
	    </div>
	    <div class="col-md-6">
	      <ul class="bottom_ul">
	      	<li><%= link_to 'Home', root_path %></li> <!-- home link -->
			<li><%= link_to 'About', public_about_path %></li> <!-- about link -->
			<li><%= link_to 'Team', public_team_path %></li> <!-- team link -->
			<li><%= link_to 'Gallery', public_gallery_path %></li> <!-- team link -->
	      </ul>
	    </div>
	  </div>
	</div>
</footer>

app/views/layouts/app/_nav_links.html.erb
<li><%= link_to 'Home', root_path %></li> <!-- home link -->

<% if !devise_controller? %>
	<% if @services.count > 0 %>
	<li class="dropdown">
	  <a href="#service" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Service <span class="caret"></span></a>
	  <ul class="dropdown-menu">
	    <% @services.each do |service| %>
	      <li><%= link_to service.name, public_listing_path(:product_id => service.id) %></li>
	    <% end %>
	  </ul>
	</li>
	<% end %> <!-- services link -->

	<% if @products.count > 0 %>
	<li class="dropdown">
	  <a href="#product" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product <span class="caret"></span></a>
	  <ul class="dropdown-menu">
	    <% @products.each do |product| %>
	    <li><%= link_to product.name, public_listing_path(:product_id => product.id) %></li>
	    <% end %>
	  </ul>
	</li>
	<% end %> <!-- products link -->
<% end %>

app/views/layouts/app/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><%= current_user.email %></b> <span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to(edit_user_registration_path) do %>
					<i class="fa fa-user-plus"></i> Edit account
				<% end %>
			</li>
		  	<li>
		  		<%= link_to(destroy_user_session_path, :method=>'delete') do %>
		  			<i class="fa fa-sign-out"></i> Sign Out
		  		<% end %>
		  	</li>
		</ul>
	</li>
<% else %>
	<li><p class="navbar-text hidden-xs hidden-sm">Already have an account?</p></li>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
		<ul id="login-dp" class="dropdown-menu">
			<li>
				<div class="row">
					<div class="col-md-12">
						Login via
						<div class="social-buttons">
							<a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
							<a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
						</div>
					    or
						<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %> 
							<div class="form-group">
								 <label class="sr-only" for="inputEmail">Email address</label>
								 <%= f.email_field(:email, class: "form-control", id: "inputEmail",placeholder: "Email address" , autofocus: true) %>
							</div>
							<div class="form-group">
								 <label class="sr-only" for="inputPwd">Password</label>
								 <%= f.password_field(:password, class: "form-control", id: "inputPwd", placeholder: "Password", autocomplete: "off") %>
					             <div class="help-block text-right"><%= link_to "Forgot your password?", new_password_path(resource_name) %></div>
							</div>
							<div class="form-group">
								<%= f.submit("Sign in", class: "btn btn-primary btn-block") %>
							</div>
							<div class="checkbox">
								 <label>
								 <%= f.check_box :remember_me %> keep me logged-in
								 </label>
							</div>

						<% end %>
					</div>
					<div class="bottom text-center">
						New here ? <%= link_to 'Join Us', new_user_registration_path %>
					</div>
				</div>
			</li>
		</ul>
	</li>  
<% end %>

app/views/layouts/app/_navigation.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top"  id="nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Astro Site', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= render 'layouts/app/nav_links' %>
          <%= render "layouts/app/nav_links_for_auth" %>
          <% if user_signed_in? %>
          <li class="cart-text">
            <%= render 'layouts/app/cart_text' %>
          </li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->
</header>