config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => 'public#home'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'public/about'
  get 'public/team'
  get 'public/listing'
  get 'public/listing_detail'
  get 'public/gallery'
  get 'public/cart'

  # resource :cart, only: [:show]
  resources :order_items, only: [:create, :destroy]

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :products do
    member do
      get :delete, :toggle_visible
    end
  end
  
  resources :listings do
    member do
      get :delete, :toggle_visible
    end
  end

  resources :teams do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	acts_as_list
	
	has_many :listings, :dependent => :destroy

	scope :visible, lambda { where(:visible => true) }
  	scope :invisible, lambda { where(:visible => false) }
  	scope :sorted, lambda { order("name ASC") }
  	scope :newest_first, lambda { order("created_at DESC") }
  	scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }
  	scope :category_group, lambda {|ctype| where(:category => ctype) }

  	

  	validates :name, :presence => true,
					 :length => { :maximum => 255 },
					 :uniqueness => { :case_sensitive => false }
	validates_presence_of :description
	validates_presence_of :category
	validates_presence_of :icon_path
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in
  before_action :set_product_count, :only => [:new, :create, :edit, :update]

  def index
    @products = Product.sorted
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Category created successfully."
      redirect_to(products_path)
    else
      render "new.js.erb"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "Category '#{@product.name}' updated successfully."
      redirect_to(products_path)
    else
      render "edit.js.erb"
    end
  end

  def toggle_visible
    @product = Product.find(params[:id])
    @product.toggle(:visible)
    @product.save
    flash[:notice] = "Category visibility toggled successfully."
    respond_to do |format|
        format.js
    end
  end

  def delete
    @product = Product.find(params[:id])
  end

  def destroy
    @products = Product.sorted
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Category '#{@product.name}' destroyed successfully."
    redirect_to(products_path)   
  end

private

  def product_params
    params.require(:product).permit(:name, :description, :category, :icon_path, :visible, :position)
  end

  def set_product_count
    @product_count = Product.count
    if params[:action] == 'new' || params[:action] == 'create'
      @product_count += 1
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
	def product_icon(product)
		if product.icon_path?
			image_tag(product.icon_path, size: "30x30")
		else
			image_tag(File.join('icons' , 'icon1.svg'), size: "30x30")
		end
	end
end

app/views/products/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 class="text-danger">Delete Category</h3>
    </div>
    <div class="modal-body">
      <ul class="errors"></ul>
      Are you sure you wish to delete <b><%= @product.name %></b>?
    </div>
    <div class="modal-footer">
      <%= link_to "Yes, Delete This Category", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
      <%= link_to "No, Please Don't", "#", class: "btn btn-success", data: { dismiss: "modal" } %>
    </div>
  </div>
</div>

app/views/products/_edit.html.erb
<div class="container">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			  	<h3 class="text-success"><%= "#{@product.name}" %></h3>
			</div>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/products/_form.html.erb
<%= form_for @product, remote: true, html: { style: "display:inline;" } do |f| %>
<%= error_messages_for(f.object) %>
<% @images = Dir.glob(File.join(Rails.root, 'app', 'assets', 'images', 'icons', '*.svg')) %>

<div class="modal-body">
    <ul class="errors"></ul>
    <div class="row">
        <div class="col-sm-6" style="padding-bottom: 10px;">
            <%= f.text_field(:name, class: 'text-cp form-control', placeholder: 'Category Name') %>
        </div>
        <div class="col-sm-6" style="padding-bottom: 10px;">
            <%= f.select(:position, 1..@product_count, {class: 'form-control'}) %> (position)
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.select(:category, [['Service', 'SERVICE'],['Product','PRODUCT']], {}, {class: 'form-control'}) %>
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.select(:visible, [ ["Visible", true], ["Invisible", false]], {}, {class: 'form-control'}) %>
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <%= f.text_area(:description, class: 'form-control', rows:'6', placeholder: 'Describe in detail....') %>
        </div>
        <div class="col-sm-12" style="padding-bottom: 10px;">
            <div class="container-fluid">
                <div class="row photogrid">
                    <% @images.each do |image| %>
                    <% @path = File.join('icons', image.split('/').last) %>
                        <%= f.radio_button(:icon_path, @path, class: 'radio-inline') %>
                        <%= image_tag(@path, size: "20x20") %>

                    <% end %>
                </div>
            </div>
        </div>
    </div>       
</div>
<div class="modal-footer">
    <%= link_to "Close", "#", class: "btn btn-secondary", data: {dismiss: "modal"} %>
    <%= f.submit "Submit" ,class: "btn btn-primary" %>
</div>

<% end %>

app/views/products/_index.html.erb
<% @products.each do |product| %>
<tr> 
    <td><%= product.position %></td>
    <td>
        <%= product.name %>
        <% if product.visible %>
            <%= link_to(toggle_visible_product_path(product), 
                :remote => true) do %>
                <i class="fa fa-eye fa-fw" aria-hidden="true"></i>
            <% end %>  
        <% else %>
            <%= link_to(toggle_visible_product_path(product), 
                :remote => true) do %>
                <i class="fa fa-eye-slash fa-fw" aria-hidden="true"></i>
            <% end %>      
        <% end %>
        <% if product.icon_path? %>
            <i class="fa fa-camera fa-fw" aria-hidden="true"></i>
        <% end %>       
    </td>
    <td>
      <%= product.category.capitalize %>
    </td>  
    <td>
      <%= truncate(product.description, :length => 30) %>
    </td>
    <td>
        <%= link_to(product_path(product), 
            :remote => true, 
            :class => "btn btn-info btn-circle") do %>
            <i class="fa fa-flag fa-fw" aria-hidden="true"></i> 
        <% end %>  
        <%= link_to(edit_product_path(product), 
            :remote => true, 
            :class => "btn btn-success btn-circle") do %>
            <i class="fa fa-edit fa-fw" aria-hidden="true"></i> 
        <% end %>  
        <%= link_to(delete_product_path(product), 
            :remote => true,
            :class => "btn btn-danger btn-circle") do %>
            <i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> 
        <% end %>        
    </td>
    <td>
        <%= link_to(listings_path(:product_id => product.id), 
            :class => "btn btn-primary btn-circle") do %>
            <i class="fa fa-list fa-fw"></i>
        <% end %>          
    </td>
</tr>
<% end %>

app/views/products/_new.html.erb
<div class="container">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 class="text-success">Add Category</h3>
			</div>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= j (render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/products/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 class="text-info"><%= @product.name %> <%= product_icon(@product) %></h3> 
        <h4 class="text-muted"><%= @product.category %></h4>   
    </div>
    <div class="modal-body">
      <p><%= @product.description %></p>
    </div>
    <div class="modal-footer">
      <%= link_to "Close", "#", class: "btn btn-secondary", data: {dismiss: "modal"} %>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<%= render "save" %>

app/views/products/destroy.js.erb
<%= render "save" %>

app/views/products/edit.js.erb
$("#product-modal").html("<%= j (render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<% @page_title = "All Categories" %>

<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header text-danger">
      <i class="fa fa-th-list"></i> 
      Categories
      <span class="badge"><%= @products.count %></span>
    </h3>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-laptop"></i><%= link_to "Dashboard", admin_path %>
      </li>
      <li><i class="fa fa-th-list"></i>Categories</li>                
    </ol>
  </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
              <p>
              <%= link_to(new_product_path, 
                  remote: true,
                  class: "btn btn-success btn-sm") do %>
                  <span class="btn-label">
                    <i class="fa fa-plus"></i> 
                  </span> Category
              <% end %>
              </p>
            </header>
            
            <table class="table table-striped table-advance table-hover" id="dataTables-product">
             <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Category</th>
                  <th>Description</th>
                  <th><i class="fa fa-wrench"></i> Action</th>
                  <th>Listings</th>
                </tr>                           
             </thead>
            <tbody class="product-index">
              <%= render "index" %>
            </tbody>
          </table>
        </section>
    </div>
</div>
<div id="product-modal" class="modal fade"></div>

app/views/products/new.js.erb
$("#product-modal").html("<%= j (render 'new') %>")
$("#product-modal").modal("show")

app/views/products/show.js.erb
$("#product-modal").html("<%= j (render 'show') %>")
$("#product-modal").modal("show")

app/views/products/update.js.erb
<%= render "save" %>